# -*- coding: utf-8 -*-
"""Healthcare 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XyG4zs6jMX5nPF7UvHA0QOzYXElQjVaM
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("Healthcare.csv")

df.columns

df.isnull()

df.isnull().sum()

df['Date of Admission']=pd.to_datetime(df['Date of Admission'])
df['Discharge Date']=pd.to_datetime(df['Discharge Date'])

df["No_of_days_stay"]=df["Discharge Date"]-df["Date of Admission"]

df['No_of_days_stay'].head()

billing=df.groupby(['Medical Condition','Insurance Provider'])['Billing Amount'].sum().unstack()
billing

billing.plot(kind='bar',figsize=(10,6), stacked=True)

plt.figure(figsize=(10,6))
sns.violinplot(data=df,
               x='Medical Condition',
               y='Billing Amount')

plt.figure(figsize=(10,6))
sns.violinplot(data=df,
               x='Insurance Provider',
               y='Billing Amount')

df['Admission Month']=df['Date of Admission'].dt.month
df['Admission Month']

monthly_sub=df.groupby('Admission Month').size()
monthly_sub

monthly_sub.plot()

Corr_matrix=df[['Age','No_of_days_stay', 'Billing Amount']].corr()
Corr_matrix

sns.heatmap(Corr_matrix, annot=True, cmap="coolwarm")