# -*- coding: utf-8 -*-
"""Healthcare 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_4jaLNMJa6w1PLusO6QLv4YlIxJU3Nx2
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("healthcare_dataset.csv")

df.head(10)

df.tail(20)

df.columns



df.dtypes

df.info

df.isnull()

df.isnull().sum()

df['Medical_Code'].isnull().sum()

df['Medical_Code']=df['Medical_Condition'].fillna('unknown')

df['Medical_Code'].isnull().sum()

df['Admission_Date']=pd.to_datetime(df['Admission_Date'])
df['Discharge_Date']=pd.to_datetime(df['Discharge_Date'])
df['Discharge_Date']

df["Admission_Type"]=(
    df["Admission_Type"]
    .str.strip()
    .str.lower()
)

df['Admission_Type'].value_counts()

df['Billing_Amount'].describe()

df['Stay_Days']=(df['Discharge_Date']-df['Admission_Date']).dt.days
df['Stay_Days']

df['Stay_Days'].describe()

pd.crosstab(df['Medical_Condition'],df['Gender'])

