# -*- coding: utf-8 -*-
"""Apple Stock Data Understanding, Cleaning & Exploratory Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14duIwXCx5AgMRQr9iCLjvGPWQtEYHmtb
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df=pd.read_csv("APPLE.csv")

df.head()

df.tail()

df.info()

df.columns

df.dtypes

print(df.describe)

df.isnull().sum()

df.drop_duplicates

df['Date']

avgopen=df['Open'].mean()
avgclose=df['Close'].mean()

print(avgopen)
print(avgclose)

df['High'].sort_values
df['Low'].sort_values

highval=df['High'].tail(1)
lowval=df['Low'].head(1)

print(highval)
print(lowval)

df['Delta']=df['Close']-df['Low']
df['Delta'].tail(10)

df['Daily_Return']=(df['Delta']/df['Open'])*100
print(df['Daily_Return'])

df['Daily_Return'].sort_values
df['Daily_Return'].tail(10)

max=df['Volume'].max()
min=df['Volume'].min()
avg=df['Volume'].mean()
print(avg)
print(min)
print(max)

df['Volume'].sort_values
df['Volume'].tail(10)