# -*- coding: utf-8 -*-
"""Apple Stock Visualization, Time-Series Analysis & Financial Insights.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uWMBhNNC4uvmJWV3UfIoiqQ2mPJx3Tsp
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("APPLE.csv")

df.columns

df["DATE"] = pd.to_datetime(df["Date"],utc=True)

df = df.sort_values("DATE")

plt.figure(figsize=(16, 8))

plt.plot(df.index, df["Open"], label="open")
plt.plot(df.index, df["High"], label="high")
plt.plot(df.index, df["Low"], label="low")
plt.plot(df.index, df["Close"], label="close")

plt.title("Apple Stock Chart")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.show()

plt.figure(figsize=(16, 8))

plt.plot(df['DATE'], df["Volume"], label="volume")

plt.title("Date Volume Analysis")
plt.xlabel("Date")
plt.ylabel("Volume")
plt.legend()
plt.show()

df["MA20"] = df["Close"].rolling(window=20).mean()

df["MA50"] = df["Close"].rolling(window=50).mean()

plt.figure(figsize=(16, 8))

plt.plot(df['DATE'], df['MA20'])

plt.title("DAY 20 Stock Detail")
plt.xlabel("Date")
plt.ylabel("price")
plt.legend()
plt.show()

plt.figure(figsize=(16, 8))

plt.plot(df['DATE'], df['MA50'])

plt.title("DAY 20 Stock Detail")
plt.xlabel("Date")
plt.ylabel("price")
plt.legend()
plt.show()

df['Daily_Return'] = df['Close'].pct_change()

plt.figure(figsize=(16, 8))
plt.histplot(
    df['Daily_Return'].dropna()
    bin(50)
    KDE=True
    plt.title("Histogram Plot")
    plt.xlabel("Return")
    plt.ylabel("price")
)