# -*- coding: utf-8 -*-
"""TASK 9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18jsHP8cKsWllYlHk6aaN--MYidWw4hoR
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("StudentsPerformance_Preprocessed.csv")

avg=df.groupby(["parental level of education","lunch"])[
    ["math score","reading score","writing score"]
].mean()

avg.plot(kind="bar",figsize=(12,6))

plt.title("Average Scores by Parental Education and Lunch Type")
plt.xlabel("Parental Education and Lunch Type")
plt.ylabel("Average Score")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(
    x="test preparation course",
    y="math score",
    data=df
)

plt.title("Math Score Variance Based on Test Preparation")
plt.xlabel("Test Preparation")
plt.ylabel("Math Score")
plt.show()

plt.figure(figsize=(7,5))

sns.scatterplot(
    x="math score",
    y="reading score",
    data=df
)

plt.title("Math Score vs Reading Score")
plt.show()

plt.figure(figsize=(7,5))

sns.scatterplot(
    x="math score",
    y="writing score",
    data=df
)

plt.title("Math Score vs Writing Score")
plt.show()

plt.figure(figsize=(7,5))

sns.scatterplot(
    x="reading score",
    y="writing score",
    data=df
)

plt.title("Reading Score vs Writing Score")
plt.show()

correlation=df[
    ["math score","reading score","writing score"]
].corr()

plt.figure(figsize=(7,5))

sns.heatmap(
    correlation,
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Between Math, Reading and Writing Scores")
plt.show()