# -*- coding: utf-8 -*-
"""Superstore 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/167Y1KTdvommvuPy8rCDd1nCeUVTVIHjE
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from scipy import stats

# This cell previously had a syntax error. Updating it to point to the correct path.
path = '/content/SampleSuperstore.csv'
print(f"Path set to: {path}")

import os
print(os.listdir('/content/'))

print(df.head())

print(df.info())

print(df.isnull().sum())

print("Average Sales:", np.mean(df["Sales"]))

sales_by_category = df.groupby("Category")["Sales"].sum()

plt.figure(figsize=(8,5))
plt.bar(sales_by_category.index, sales_by_category.values)
plt.title("Sales by Category")
plt.xlabel("Category")
plt.ylabel("Total Sales")
plt.xticks(rotation=90)
plt.show()

plt.figure(figsize=(8,5))
plt.hist(df["Sales"], bins=30, edgecolor="black")
plt.title("Sales Distribution")
plt.xlabel("Sales")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(data=df, x="Sales", y="Profit", alpha=0.5)
plt.title("Sales vs Profit")
plt.show()

X_train, X_test = train_test_split(df, test_size=0.2, random_state=42)

print("Split completed successfully.")
print(f"Training Rows: {len(X_train)}")
print(f"Testing Rows: {len(X_test)}")

print("Mean Sales:", stats.tmean(df["Sales"]))